3project3/account/urls.py
from django.urls import path 
from account import views

app_name = "account"

urlpatterns = [
    path("login/",views.login, name="login"),
    path("register/",views.register, name="register"),
]

3project3/chat/urls.py
from django.urls import path
from chat import views

app_name = "chat"
# handler404 = 'chat.views.not_found_view'

urlpatterns = [
    path("ccontact/", views.ccontact, name="ccontact"),
    path("chome/", views.chome, name="chome"),
]

3project3/payment/urls.py
from django.urls import path
from payment import views

app_name = "payment"
# handler404 = 'chat.views.not_found_view'

urlpatterns = [
    path("pcontact/", views.pcontact, name="pcontact"),
    path("phome/", views.phome, name="phome"),
]

3project3/pro3/urls.py
from django.contrib import admin
from django.urls import path, include
from pro3 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("base/",views.base,name="base"),
    path("home/",views.home,name="home"),
    path("chat/",include("chat.urls")),
    path("payment/",include("payment.urls")),
    path("account/",include("account.urls")),
    # this used to send or request the data from one file to another file 
    path("database/",views.database,name="database"),
    path("datahome/<ind>/<data>/",views.datahome,name="datahome"),
    path("sbase/",views.sbase, name="sbase"),
    path("shome/<data>/",views.shome, name="shome"),
]

3project3/account/models.py
from django.db import models

# Create your models here.

3project3/chat/models.py
from django.db import models

# Create your models here.

3project3/payment/models.py
from django.db import models

# Create your models here.

3project3/account/views.py
from django.shortcuts import render

# Create your views here.

def login(request):
    return render(request, 'login.html')

def register(request):
    return render(request, 'register.html')

3project3/chat/views.py
from django.shortcuts import render

# Create your views here.


def chome(request):
    return render(request, "chome.html")
    
def ccontact(request):
    return render(request, "ccontact.html")

3project3/payment/views.py
from django.shortcuts import render

# Create your views here.


def phome(request):
    return render(request, "phome.html")
    
def pcontact(request):
    return render(request, "pcontact.html")

3project3/pro3/views.py
from django.shortcuts import render

# def home(request):
#     return render(request, "home.html")
    
# def base(request):
#     return render(request, "base.html")


# # help to send or request the data from one file to another file\

# def datahome(request,ind, data):
#     return render(request, "datahome.html",{"ind": ind,'data':data})
    
# def database(request):
#     data = "this is my home i will not leve"
#     ind=1
#     return render(request, "database.html",{"data":data,"ind":ind})



def shome(request,data):
    return render(request, 'shome.html',{'data':data}) 


def sbase(request):
    data = "jiya "
    return render(request, 'sbase.html',{"data": data}) 

3project3/chat/templates/ccontact.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>this is chat contact page</h1>
    <li>
      <a href="{% url 'chat:chome' %}">to chat home page</a>
    </li>
    <li>
      <a href="{% url 'base' %}"> to generic base page </a>
    </li>
    <li>
      <a href="{% url 'home' %}"> to generic home page </a>
    </li>
    <li>
      <a href="{% url 'payment:phome' %}"> to payment home page</a>
    </li>
    <li>
      <a href="{% url 'payment:pcontact' %}"> to payment contact page</a>
    </li>
    <li>
      <a href="{% url 'chat:chome' %}"> to chat home page</a>
    </li>
    <li>
      <a href="{% url 'chat:ccontact' %}"> to chat contact page</a>
    </li>
  </body>
</html>

3project3/chat/templates/chome.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>chat home page</h1>
    <li>
      <a href="{% url 'chat:ccontact' %}">to chat contact page</a>
    </li>
    <li>
      <a href="{% url 'home' %}"> to generic home page </a>
    </li>
    <li>
      <a href="{% url 'base' %}"> to generic base page </a>
    </li>
    <li>
      <a href="{% url 'payment:phome' %}"> to payment home page</a>
    </li>
    <li>
      <a href="{% url 'payment:pcontact' %}"> to payment contact page</a>
    </li>
    <li>
      <a href="{% url 'chat:chome' %}"> to chat home page</a>
    </li>
    <li>
      <a href="{% url 'chat:ccontact' %}"> to chat contact page</a>
    </li>
  </body>
</html>