12project/app1/urls.py
from django.urls import path
from app1 import views
urlpatterns = [
    path('create_student/',views.create_student,name='create_student'),
    path('update_student/<int:pk>/',views.update_student,name='update_student'),
    path('read_student/',views.read_student,name='read_student'),
]

12project/formcrudoperation/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls')),
]

12project/app1/models.py
import email
from django.db import models

# Create your models here.

class Student(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.PositiveBigIntegerField()
    email = models.EmailField()
    password = models.CharField(max_length=50)

12project/app1/forms.py
from operator import ipow
from pyexpat import model
from django import forms
from app1.models import Student

class StudentForm(forms.Form):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    phone = forms.IntegerField()
    email = forms.EmailField()
    password = forms.CharField(max_length=50)

12project/app1/views.py
import email
from django.http import HttpResponse
from django.shortcuts import render
from app1.forms import StudentForm
from app1.models import Student

# Create your views here.

def create_student(request):    
    sform = StudentForm()
    print(sform)
    if request.method == 'POST':        
        Student.objects.create(first_name = request.POST['first_name'],
        last_name = request.POST['last_name'],
        phone= request.POST['phone'],
        email = request.POST['email'],
        password = request.POST['password'])
    return render(request, 'create_student.html', {'sform':sform})

def update_student(request,pk):
    sdata = Student.objects.get(id=pk)
    if request.method == 'POST':
        Student.objects.filter(id=pk).update(
        first_name = request.POST['first_name'],
        last_name = request.POST['last_name'],
        phone= request.POST['phone'],
        email = request.POST['email'],
        password = request.POST['password'])
        return HttpResponse("data is updated") 
    return render(request, 'update_student.html',{'sdata':sdata})


def read_student(request):
    res = Student.objects.all()
    data = ""
    for i in res:
        data = data + f'first name {i.first_name} last name {i.last_name} phone {i.phone} email {i.email} password {i.password}  '
        
    return HttpResponse(data)

12project/app1/templates/create_student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>create data in page </h1>
    <form method="POST">
        {% csrf_token %}
        {{sform.as_p}}
        <input type="submit" value="create" />
    </form>
</body>
</html>

12project/app1/templates/update_student.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>this is update data</h1>
    <form method="POST">
        {% csrf_token %}
      <tr>
        <th><label for="id_first_name">First name:</label></th>
        <td>
          <input
            type="text"
            name="first_name"
            maxlength="50"
            required
            id="id_first_name"
            value="{{sdata.first_name}}"
          />
        </td>
      </tr><br />

      <tr>
        <th><label for="id_last_name">Last name:</label></th>
        <td>
          <input
            type="text"
            name="last_name"
            maxlength="50"
            required
            id="id_last_name"
            value="{{sdata.last_name}}"
          />
        </td>
      <tr> <br />
        <th><label for="id_Phone">Phone:</label></th>
        <td>
          <input
            type="number"
            name="phone"
            required
            id="id_phone"
            value="{{sdata.phone}}"
          />
        </td>
      <tr> <br />
        <th><label for="id_email">Last name:</label></th>
        <td>
          <input
            type="email"
            name="email"
            required
            id="id_email"
            value="{{sdata.email}}"
          />
        </td>
      </tr><br />
      <tr>
        <th><label for="id_password">Last name:</label></th>
        <td>
          <input
            type="password"
            name="password"
            required
            id="id_password"
            value="{{sdata.password}}"
          />
        </td>
      </tr><br />
      <input type="submit" value="submit" />
      <input type="reset" value="reset" />
    </form>
  </body>
</html>